#Importing the necessary modules needed for analysis

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import sklearn
import matplotlib.pyplot as plt
import matplotlib as matplot
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split

#Reading the UNSW-NB15 traning dataset into the analysis

In [2]:
tesst = pd.read_csv ('UNSW_NB15_training-set.csv')
tesst.head()

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,udp,-,INT,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,udp,-,INT,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,udp,-,INT,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,udp,-,INT,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,udp,-,INT,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

#Identifying the types of attacks in the dataset

In [3]:
print(tesst['label'].unique())
print(tesst['attack_cat'].unique())

[0 1]
['Normal' 'Reconnaissance' 'Backdoor' 'DoS' 'Exploits' 'Analysis'
 'Fuzzers' 'Worms' 'Shellcode' 'Generic']

#Identifying the data types for the columns needed for analysis(protocol, service, state, attack_cat)

In [4]:
mask = (tesst.dtypes == np.object) 
print(tesst.loc[:,mask].head())
list_cat = tesst.loc[:,mask].columns.tolist()
print(list_cat)
print(tesst.loc[:,mask].values)

  proto service state attack_cat
0   udp       -   INT     Normal
1   udp       -   INT     Normal
2   udp       -   INT     Normal
3   udp       -   INT     Normal
4   udp       -   INT     Normal
['proto', 'service', 'state', 'attack_cat']
[['udp' '-' 'INT' 'Normal']
 ['udp' '-' 'INT' 'Normal']
 ['udp' '-' 'INT' 'Normal']
 ...
 ['arp' '-' 'INT' 'Normal']
 ['arp' '-' 'INT' 'Normal']
 ['udp' '-' 'INT' 'Normal']]

/var/folders/jy/v64pg74x3jqbsvprrb0xs_x80000gn/T/ipykernel_20706/900401816.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = (tesst.dtypes == np.object)

In [16]:
le_proto = LabelEncoder().fit(tesst['proto'])
tesst['proto'] =le_proto.transform(tesst['proto'])
lb_proto = LabelBinarizer().fit(tesst['proto'])
tesst['proto'] = lb_proto.transform(tesst['proto'])

In [5]:
mask = (tesst.dtypes != np.object)
print(tesst.loc[:,mask].head())
list_cat = tesst.loc[:,mask].columns.tolist()
print(list_cat)
tesst.loc[:,mask].describe()

   id       dur  spkts  dpkts  sbytes  dbytes         rate  sttl  dttl  \
0   1  0.000011      2      0     496       0   90909.0902   254     0
1   2  0.000008      2      0    1762       0  125000.0003   254     0
2   3  0.000005      2      0    1068       0  200000.0051   254     0
3   4  0.000006      2      0     900       0  166666.6608   254     0
4   5  0.000010      2      0    2126       0  100000.0025   254     0

         sload  ...  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  \
0  180363632.0  ...                 1                 1               2
1  881000000.0  ...                 1                 1               2
2  854400000.0  ...                 1                 1               3
3  600000000.0  ...                 2                 1               3
4  850400000.0  ...                 2                 1               3

   is_ftp_login  ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  \
0             0           0                 0           1           2
1             0           0                 0           1           2
2             0           0                 0           1           3
3             0           0                 0           2           3
4             0           0                 0           2           3

   is_sm_ips_ports  label
0                0      0
1                0      0
2                0      0
3                0      0
4                0      0

[5 rows x 41 columns]
['id', 'dur', 'spkts', 'dpkts', 'sbytes', 'dbytes', 'rate', 'sttl', 'dttl', 'sload', 'dload', 'sloss', 'dloss', 'sinpkt', 'dinpkt', 'sjit', 'djit', 'swin', 'stcpb', 'dtcpb', 'dwin', 'tcprtt', 'synack', 'ackdat', 'smean', 'dmean', 'trans_depth', 'response_body_len', 'ct_srv_src', 'ct_state_ttl', 'ct_dst_ltm', 'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'is_ftp_login', 'ct_ftp_cmd', 'ct_flw_http_mthd', 'ct_src_ltm', 'ct_srv_dst', 'is_sm_ips_ports', 'label']

/var/folders/jy/v64pg74x3jqbsvprrb0xs_x80000gn/T/ipykernel_20706/2259840498.py:1: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = (tesst.dtypes != np.object)

,id,dur,spkts,dpkts,sbytes,dbytes,rate,sttl,dttl,sload,...,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,label
count,82332.000000,82332.000000,82332.000000,82332.000000,8.233200e+04,8.233200e+04,8.233200e+04,82332.000000,82332.000000,8.233200e+04,...,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000,82332.000000
mean,41166.500000,1.006756,18.666472,17.545936,7.993908e+03,1.323379e+04,8.241089e+04,180.967667,95.713003,6.454902e+07,...,4.928898,3.663011,7.456360,0.008284,0.008381,0.129743,6.468360,9.164262,0.011126,0.550600
std,23767.345519,4.710444,133.916353,115.574086,1.716423e+05,1.514715e+05,1.486204e+05,101.513358,116.667722,1.798618e+08,...,8.389545,5.915386,11.415191,0.091171,0.092485,0.638683,8.543927,11.121413,0.104891,0.497436
min,1.000000,0.000000,1.000000,0.000000,2.400000e+01,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000e+00,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000
25%,20583.750000,0.000008,2.000000,0.000000,1.140000e+02,0.000000e+00,2.860611e+01,62.000000,0.000000,1.120247e+04,...,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000
50%,41166.500000,0.014138,6.000000,2.000000,5.340000e+02,1.780000e+02,2.650177e+03,254.000000,29.000000,5.770032e+05,...,1.000000,1.000000,3.000000,0.000000,0.000000,0.000000,3.000000,5.000000,0.000000,1.000000
75%,61749.250000,0.719360,12.000000,10.000000,1.280000e+03,9.560000e+02,1.111111e+05,254.000000,252.000000,6.514286e+07,...,4.000000,3.000000,6.000000,0.000000,0.000000,0.000000,7.000000,11.000000,0.000000,1.000000
max,82332.000000,59.999989,10646.000000,11018.000000,1.435577e+07,1.465753e+07,1.000000e+06,255.000000,253.000000,5.268000e+09,...,59.000000,38.000000,63.000000,2.000000,2.000000,16.000000,60.000000,62.000000,1.000000,1.000000

In [6]:
tesst.attack_cat.value_counts()

Normal            37000
Generic           18871
Exploits          11132
Fuzzers            6062
DoS                4089
Reconnaissance     3496
Analysis            677
Backdoor            583
Shellcode           378
Worms                44
Name: attack_cat, dtype: int64

In [35]:
mask = (tesst.label == 1)
print(tesst.loc[mask,:].service.value_counts())
print(tesst.loc[mask,:].proto.value_counts())
mask.head()

-           19778
dns         18299
http         4274
smtp         1216
ftp           794
ftp-data      447
pop3          423
ssl            30
snmp           29
dhcp           26
radius          7
irc             5
ssh             4
Name: service, dtype: int64
udp           21321
tcp           15247
unas           3515
ospf            638
sctp            324
              ...
wb-mon           32
br-sat-mon       32
pvp              32
wsn              32
ib               31
Name: proto, Length: 129, dtype: int64

0    False
1    False
2    False
3    False
4    False
Name: label, dtype: bool

In [34]:
mask = (tesst.label == 0)
print(tesst.loc[mask,:].service.value_counts())
print(tesst.loc[mask,:].proto.value_counts())
mask.head()
mask.tail()

-           27375
http         4013
dns          3068
ftp-data      949
ftp           758
smtp          635
ssh           200
radius          2
Name: service, dtype: int64
tcp     27848
udp      8097
arp       987
ospf       38
igmp       30
Name: proto, dtype: int64

82327    True
82328    True
82329    True
82330    True
82331    True
Name: label, dtype: bool

In [9]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()
num_cat = le.fit_transform(tesst.attack_cat)
print(le.classes_)
print(np.unique(num_cat))

['Analysis' 'Backdoor' 'DoS' 'Exploits' 'Fuzzers' 'Generic' 'Normal'
 'Reconnaissance' 'Shellcode' 'Worms']
[0 1 2 3 4 5 6 7 8 9]

In [10]:
Y=num_cat.tolist()
X = tesst.drop(columns=['id','attack_cat','label']) 
mask = (X.dtypes == np.object)
list_cat = X.loc[:,mask].columns.tolist()
list_cat

/var/folders/jy/v64pg74x3jqbsvprrb0xs_x80000gn/T/ipykernel_20706/1899963662.py:3: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  mask = (X.dtypes == np.object)

['proto', 'service', 'state']

In [11]:
X = pd.get_dummies(X, columns=list_cat)
X.head()
Y[:10]

[6, 6, 6, 6, 6, 6, 6, 6, 6, 6]

In [12]:
import sklearn
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)

In [22]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-1.5.2-py3-none-macosx_10_15_x86_64.macosx_11_0_x86_64.macosx_12_0_x86_64.whl (1.3 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 1.3 MB 1.9 MB/s eta 0:00:01
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from xgboost) (1.22.2)
Requirement already satisfied: scipy in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from xgboost) (1.8.0)
Installing collected packages: xgboost
Successfully installed xgboost-1.5.2
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

In [20]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn import svm
from sklearn.metrics import classification_report,roc_auc_score,average_precision_score,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier as xgb
from sklearn.ensemble import IsolationForest
from sklearn.tree import DecisionTreeClassifier

In [31]:
params = {
    'max_depth': 10,
    'objective': 'multi:softmax',  
    'num_class': 10,                
    'n_gpus': 1
}

clf3 = GradientBoostingClassifier()

In [17]:
le_service = LabelEncoder().fit(tesst['service'])
tesst['service'] =le_service.transform(tesst['service'])
lb_service = LabelBinarizer().fit(tesst['service'])
tesst['service'] = lb_service.transform(tesst['service'])

In [18]:
le_flag = LabelEncoder().fit(tesst['state'])
tesst['state'] =le_flag.transform(tesst['state'])
tesst.head()

,id,dur,proto,service,state,spkts,dpkts,sbytes,dbytes,rate,...,ct_dst_sport_ltm,ct_dst_src_ltm,is_ftp_login,ct_ftp_cmd,ct_flw_http_mthd,ct_src_ltm,ct_srv_dst,is_sm_ips_ports,attack_cat,label
0,1,0.000011,0,1,4,2,0,496,0,90909.0902,...,1,2,0,0,0,1,2,0,Normal,0
1,2,0.000008,0,1,4,2,0,1762,0,125000.0003,...,1,2,0,0,0,1,2,0,Normal,0
2,3,0.000005,0,1,4,2,0,1068,0,200000.0051,...,1,3,0,0,0,1,3,0,Normal,0
3,4,0.000006,0,1,4,2,0,900,0,166666.6608,...,1,3,0,0,0,2,3,0,Normal,0
4,5,0.000010,0,1,4,2,0,2126,0,100000.0025,...,1,3,0,0,0,2,3,0,Normal,0

In [21]:
le_class = LabelEncoder().fit(tesst['attack_cat'])
tesst['attack_cat'] =le_class.transform(tesst['attack_cat'])
tesst.head()
print (tesst)

          id       dur  proto  service  state  spkts  dpkts  sbytes  dbytes  \
0          1  0.000011      0        1      4      2      0     496       0
1          2  0.000008      0        1      4      2      0    1762       0
2          3  0.000005      0        1      4      2      0    1068       0
3          4  0.000006      0        1      4      2      0     900       0
4          5  0.000010      0        1      4      2      0    2126       0
...      ...       ...    ...      ...    ...    ...    ...     ...     ...
82327  82328  0.000005      0        1      4      2      0     104       0
82328  82329  1.106101      0        1      3     20      8   18062     354
82329  82330  0.000000      0        1      4      1      0      46       0
82330  82331  0.000000      0        1      4      1      0      46       0
82331  82332  0.000009      0        1      4      2      0     104       0

                rate  ...  ct_dst_sport_ltm  ct_dst_src_ltm  is_ftp_login  \
0       90909.090200  ...                 1               2             0
1      125000.000300  ...                 1               2             0
2      200000.005100  ...                 1               3             0
3      166666.660800  ...                 1               3             0
4      100000.002500  ...                 1               3             0
...              ...  ...               ...             ...           ...
82327  200000.005100  ...                 1               2             0
82328      24.410067  ...                 1               1             0
82329       0.000000  ...                 1               1             0
82330       0.000000  ...                 1               1             0
82331  111111.107200  ...                 1               1             0

       ct_ftp_cmd  ct_flw_http_mthd  ct_src_ltm  ct_srv_dst  is_sm_ips_ports  \
0               0                 0           1           2                0
1               0                 0           1           2                0
2               0                 0           1           3                0
3               0                 0           2           3                0
4               0                 0           2           3                0
...           ...               ...         ...         ...              ...
82327           0                 0           2           1                0
82328           0                 0           3           2                0
82329           0                 0           1           1                1
82330           0                 0           1           1                1
82331           0                 0           1           1                0

       attack_cat  label
0               6      0
1               6      0
2               6      0
3               6      0
4               6      0
...           ...    ...
82327           6      0
82328           6      0
82329           6      0
82330           6      0
82331           6      0

[82332 rows x 45 columns]

In [23]:
import csv
with open ('tesst', 'rb') as f:
    data = list(csv.reader(f))

In [20]:
x = df.drop('attack_cat', axis=1)
y = df.loc[:,['attack_cat']]
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.80, random_state=10020)

In [21]:
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import IsolationForest
from sklearn.tree import DecisionTreeClassifier

In [22]:
x = X_train
y = y_train['attack_cat'].ravel()

clf1 = DecisionTreeClassifier() 
clf2 = RandomForestClassifier(n_estimators=25, random_state=1)
clf3 = GradientBoostingClassifier()
ET = ExtraTreesClassifier(n_estimators=10, criterion='gini', max_features='auto', bootstrap=False)

eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3),('et',ET)], voting='hard') 

for clf, label in zip([clf1, clf2, clf3,ET, eclf], ['DecisionTreeClassifier', 'Random Forest', 'GradientBoostingClassifier','ExtraTreesClassifier', 'Ensemble']): 
    tmp = clf.fit(x,y)
    pred = clf.score(X_test,y_test)
    print("Acc: %0.2f [%s]" % (pred,label))

Acc: 0.87 [DecisionTreeClassifier]
Acc: 0.89 [Random Forest]
Acc: 0.89 [GradientBoostingClassifier]
Acc: 0.88 [ExtraTreesClassifier]
Acc: 0.89 [Ensemble]